scp -i ~/.ssh/okeanos_rsa -r user@snf-872411.vm.okeanos.grnet.gr:/home/user/logs1.log logs/logs1.log
scp -i ~/.ssh/okeanos_rsa -r user@snf-872412.vm.okeanos.grnet.gr:/home/user/logs2.log logs/logs2.log
scp -i ~/.ssh/okeanos_rsa -r user@snf-872414.vm.okeanos.grnet.gr:/home/user/logs3.log logs/logs3.log
scp -i ~/.ssh/okeanos_rsa -r user@snf-872415.vm.okeanos.grnet.gr:/home/user/logs4.log logs/logs4.log
scp -i ~/.ssh/okeanos_rsa -r user@snf-872416.vm.okeanos.grnet.gr:/home/user/logs5.log logs/logs5.log
scp -i ~/.ssh/okeanos_rsa -r user@snf-872433.vm.okeanos.grnet.gr:/home/user/logs6.log logs/logs6.log
scp -i ~/.ssh/okeanos_rsa -r user@snf-872783.vm.okeanos.grnet.gr:/home/user/logs7.log logs/logs7.log
scp -i ~/.ssh/okeanos_rsa -r user@snf-872784.vm.okeanos.grnet.gr:/home/user/logs8.log logs/logs8.log
scp -i ~/.ssh/okeanos_rsa -r user@snf-872785.vm.okeanos.grnet.gr:/home/user/logs9.log logs/logs9.log
scp -i ~/.ssh/okeanos_rsa -r user@snf-872786.vm.okeanos.grnet.gr:/home/user/logs10.log logs/logs10.log
scp -i ~/.ssh/okeanos_rsa -r user@snf-872787.vm.okeanos.grnet.gr:/home/user/logs11.log logs/logs11.log
scp -i ~/.ssh/okeanos_rsa -r user@snf-872788.vm.okeanos.grnet.gr:/home/user/logs12.log logs/logs12.log
scp -i ~/.ssh/okeanos_rsa -r user@snf-872789.vm.okeanos.grnet.gr:/home/user/logs13.log logs/logs13.log
scp -i ~/.ssh/okeanos_rsa -r user@snf-872790.vm.okeanos.grnet.gr:/home/user/logs14.log logs/logs14.log
scp -i ~/.ssh/okeanos_rsa -r user@snf-872791.vm.okeanos.grnet.gr:/home/user/logs15.log logs/logs15.log
scp -i ~/.ssh/okeanos_rsa -r user@snf-872792.vm.okeanos.grnet.gr:/home/user/logs16.log logs/logs16.log
scp -i ~/.ssh/okeanos_rsa -r user@snf-872793.vm.okeanos.grnet.gr:/home/user/logs17.log logs/logs17.log
scp -i ~/.ssh/okeanos_rsa -r user@snf-872794.vm.okeanos.grnet.gr:/home/user/logs18.log logs/logs18.log
scp -i ~/.ssh/okeanos_rsa -r user@snf-872795.vm.okeanos.grnet.gr:/home/user/logs19.log logs/logs19.log
scp -i ~/.ssh/okeanos_rsa -r user@snf-872796.vm.okeanos.grnet.gr:/home/user/logs20.log logs/logs20.log
