scp -i ~/.ssh/okeanos_rsa -r btc-network-data user@snf-872411.vm.okeanos.grnet.gr:/home/user/btc-network-data
scp -i ~/.ssh/okeanos_rsa -r btc-network-data user@snf-872412.vm.okeanos.grnet.gr:/home/user/btc-network-data
scp -i ~/.ssh/okeanos_rsa -r btc-network-data user@snf-872414.vm.okeanos.grnet.gr:/home/user/btc-network-data
scp -i ~/.ssh/okeanos_rsa -r btc-network-data user@snf-872415.vm.okeanos.grnet.gr:/home/user/btc-network-data
scp -i ~/.ssh/okeanos_rsa -r btc-network-data user@snf-872416.vm.okeanos.grnet.gr:/home/user/btc-network-data
scp -i ~/.ssh/okeanos_rsa -r btc-network-data user@snf-872433.vm.okeanos.grnet.gr:/home/user/btc-network-data
scp -i ~/.ssh/okeanos_rsa -r btc-network-data user@snf-872783.vm.okeanos.grnet.gr:/home/user/btc-network-data
scp -i ~/.ssh/okeanos_rsa -r btc-network-data user@snf-872784.vm.okeanos.grnet.gr:/home/user/btc-network-data
scp -i ~/.ssh/okeanos_rsa -r btc-network-data user@snf-872785.vm.okeanos.grnet.gr:/home/user/btc-network-data
scp -i ~/.ssh/okeanos_rsa -r btc-network-data user@snf-872786.vm.okeanos.grnet.gr:/home/user/btc-network-data
scp -i ~/.ssh/okeanos_rsa -r btc-network-data user@snf-872787.vm.okeanos.grnet.gr:/home/user/btc-network-data
scp -i ~/.ssh/okeanos_rsa -r btc-network-data user@snf-872788.vm.okeanos.grnet.gr:/home/user/btc-network-data
scp -i ~/.ssh/okeanos_rsa -r btc-network-data user@snf-872789.vm.okeanos.grnet.gr:/home/user/btc-network-data
scp -i ~/.ssh/okeanos_rsa -r btc-network-data user@snf-872790.vm.okeanos.grnet.gr:/home/user/btc-network-data
scp -i ~/.ssh/okeanos_rsa -r btc-network-data user@snf-872791.vm.okeanos.grnet.gr:/home/user/btc-network-data
scp -i ~/.ssh/okeanos_rsa -r btc-network-data user@snf-872792.vm.okeanos.grnet.gr:/home/user/btc-network-data
scp -i ~/.ssh/okeanos_rsa -r btc-network-data user@snf-872793.vm.okeanos.grnet.gr:/home/user/btc-network-data
scp -i ~/.ssh/okeanos_rsa -r btc-network-data user@snf-872794.vm.okeanos.grnet.gr:/home/user/btc-network-data
scp -i ~/.ssh/okeanos_rsa -r btc-network-data user@snf-872795.vm.okeanos.grnet.gr:/home/user/btc-network-data
scp -i ~/.ssh/okeanos_rsa -r btc-network-data user@snf-872796.vm.okeanos.grnet.gr:/home/user/btc-network-data
