name: ci

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: bahmutov/npm-install@v1
      - run: npm test
      - run: npm run build
